name: Triggered by serviceA

on:
  repository_dispatch:
    types: [trigger-api-store]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2