name: Triggered by serviceA

on:
  repository_dispatch:
    types: [trigger-api-store]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Python script
        run: python3 app.py
